### ISSUE TITLE
Erros no build do SIMET-MA no Docker

### ISSUE THREAD

**Issue by amorim-ipt** [simetnicbr/simet-ma#4]
Erros no build do SIMET-MA no Docker:

S.O.: Ubuntu 18.04.2 LTS
Kernel: 4.18.0-16-generic SMP x86_64 GNU/Linux

As dependências foram previamente instaladas:

$ sudo apt-get install build-essential autoconf automake libtool fakeroot debhelper libjson-c-dev cmake libcurl4-gnutls-dev pkg-config lsb-release

Foram usados os comandos recomendados na documentação:

$./autogen.sh

Não ocorreram erros.

$./configure --prefix=/opt/simet --localstatedir=/var --libdir=/opt/simet/lib --sysconfdir
=/opt/simet/etc

Não ocorreram erros.

$ sudo docker build -t simet-ma:local -f docker/Dockerfile . 

Ocorreram alguns erros:

Sending build context to Docker daemon  20.25MB 
Step 1/28 : ARG DISTRO=debian:stretch 
Step 2/28 : FROM $DISTRO 
---> 0af60a5c6dd0 
Step 3/28 : LABEL description="SIMET2 Measurement Agent builder environment" 
---> Using cache 
---> f16491abda1c 
Step 4/28 : LABEL maintainer="Henrique de Moraes Holschuh <henrique@nic.br>" 
---> Using cache 
---> cabdeba559bb 
Step 5/28 : RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get -y dist-upgrade &&     apt-get -y install --install-recommends       build-essential autoconf autom
ake libtool fakeroot debhelper 
---> Running in f3fe5a9a4c86 
Err:1 http://security.debian.org/debian-security stretch/updates InRelease 
 Could not connect to security.debian.org:80 (200.17.202.197), connection timed out 
Err:2 http://deb.debian.org/debian stretch InRelease 
 Could not connect to deb.debian.org:80 (130.89.148.14), connection timed out [IP: 130.89.148.14 80] 
Err:3 http://deb.debian.org/debian stretch-updates InRelease 
 Unable to connect to deb.debian.org:http: [IP: 130.89.148.14 80] 
Reading package lists... 
W: Failed to fetch http://deb.debian.org/debian/dists/stretch/InRelease  Could not connect to deb.debian.org:80 (130.89.148.14), connection timed out [IP: 130.89.148.14 80] 
W: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/InRelease  Could not connect to security.debian.org:80 (200.17.202.197), connection time
d out 
W: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/InRelease  Unable to connect to deb.debian.org:http: [IP: 130.89.148.14 80]                            
W: Some index files failed to download. They have been ignored, or old ones used instead.                                                                                    
Reading package lists...                                                                                                                                                     
Building dependency tree... 
Reading state information... 
Calculating upgrade... 
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded. 
Reading package lists... 
Building dependency tree... 
Reading state information... 
Package debhelper is not available, but is referred to by another package. 
This may mean that the package is missing, has been obsoleted, or 
is only available from another source 

E: Unable to locate package build-essential 
E: Unable to locate package autoconf
E: Unable to locate package automake
E: Unable to locate package libtool
E: Unable to locate package fakeroot
E: Package 'debhelper' has no installation candidate                                                                                                                         
The command '/bin/sh -c DEBIAN_FRONTEND=noninteractive apt-get update && apt-get -y dist-upgrade &&     apt-get -y install --install-recommends       build-essential autoco
nf automake libtool fakeroot debhelper' returned a non-zero code: 100 
$

**Comment by farribeiro** [comment]
Ele não está nem gerando o cache de pacotes do apt

**Comment by hmh** [comment]
A documentação (docker/README.txt, bem como os targets exemplo "docker-" no Makefile) foi atualizada recentemente, e agora menciona que é necessário habilitar acesso à rede no docker se você deseja que ele baixe alguma coisa da rede, e esse é  caso do "builder" do simet-ma.

tente:
sudo docker build --network=host -t simet-ma:local -f docker/Dockerfile .

ou alguma variação de --network que seja aplicável a sua configuração do docker.

Lembrando que o simet-ma precisa de acesso à internet para funcionar, de preferência via _host networking_ do docker (--network=host).
