### ISSUE TITLE
Visualização dos resultados ainda não está disponível

### ISSUE THREAD

**Issue by hmh** [simetnicbr/simet-ma#7]
A visualização dos resultados das medições realizadas pelo SIMET-MA **ainda não está disponível** para o público em geral.

Essa issue será atualizada à medida que os diversos sistemas de visualização de resultados (mapas temáticos, portal de acesso do provedor, portal de acesso do usuário) forem disponibilizados.

**Comment by farribeiro** [comment]
Um detalhe que não gostava do antigo gráfico é que links de tamanhos diversos dá uma interpretação errônea, primeiramente tem que saber quanto é contratado de cada usuário para se ter uma boa aferição que está atendendo o usuário.

Um exemplo hipotético: Pode acontecer que em um certa região, ofereça +100Mbits de planos e se os clientes contratam apenas ~5Mbits (me enquadro neste caso)? Ao misturar os resultado pode ter a média dos planos ativos naquela região. Isso pode ser bom para ISP descobrir o planejamento de novas expansões

Para o medição individual não fica a calhar, se estão cumprindo contratado.

**Comment by hmh** [comment]
@farribeiro, sim, você está perfeitamente correto em apontar que o uso simplista de médias [em mapas que tentam mostrar algo a respeito de uma população de medidores] não costumaria mostrar nada sequer condizente com a realidade.  Nem sequer medianas mostrariam algo coerente em muitos casos -- imagine uma região com quantidades semelhantes de usuários de 5Mpbs e de 100Mbps.  Dizer que essa região é de 5Mbps, 100Mbs (possíveis medianas) ou 55Mbps (média aritmética) seria conversa fiada.

Estamos *bem* cientes disso... o detalhe é como externar essa informação para o usuário [em um mapa], e essa parte não tem nada de óbvia.

**Comment by hmh** [comment]
Visualização de um medidor específico para saber se "estão cumprindo o contratado ou não" é um caso bem diferente, e bem mais fácil de tratar.

**Comment by farribeiro** [comment]
Mas um medidor somente é buscado para esta finalidade, não?

**Comment by hmh** [comment]
Mesmo estando sempre dentro do contratado, você poderia estar interessado em saber quão melhor ou pior fica seu acesso ao longo do dia, não?

Temos muitos perfis de usuários, isso sem levar em conta os setores da sociedade que tem interesse apenas nos dados agregados (qualidade e distribuição de velocidades em certa região, etc).

**Comment by hmh** [comment]
Visualização básica está pronta (via navegador web).  O piloto irá na SIMETBox 624, e adicionaremos um "helper" no simet-ma 0.17.0 para chamar o navegador padrão com a URL correta, e muito provavelmente uma entrada de menu nos desktops que sigam as especificações do freedesktop.org.

A URL é variável, pois inclui como parâmetro um token que pode ser renovado a qualquer momento pelo medidor (invalidando todos os tokens antigos), e é renovado por padrão a cada 24h.

**Comment by hmh** [comment]
Visualização já está disponível em produção há algum tempo.  Um comando da CLI retorna a URL ou tenta rodar o navegador diretamente, para abrir a página de resultados das medições daquele medidor.

Uma entrada de menu é adicionada ao Desktop Environment do computador, para facilitar o acesso.
